name: Ubuntu Client Smoke Test

on:
  #  workflow_dispatch:
  #    branches: [ main ]
  push:
    branches: [ version-2.0 ]
  pull_request:
    branches: [ version-2.0 ]

jobs:
  UbuntuClientSmokeTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Ubuntu With Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
